name: Auto Label Issues by Keywords

on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const body = (context.payload.issue.body || '').toLowerCase();
            const labels = [];

            const keywordLabels = {
              bug: 'bug',
              documentation: 'documentation',
              duplicate: 'duplicate',
              enhancement: 'enhancement',
              'good first issue': 'good first issue',
              'help wanted': 'help wanted',
              question: 'question',
              ui: 'UI/UX',
              ux: 'UI/UX'
            };

            for (const [keyword, label] of Object.entries(keywordLabels)) {
              if (title.includes(keyword) || body.includes(keyword)) {
                if (!labels.includes(label)) labels.push(label);
              }
            }

            if (labels.length) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels
              });
            }
